### ISSUE TITLE
Add licensing information

### ISSUE THREAD

**Issue by silverweed** [adinfinit/texpack#1]
Please, add a license to this repository to allow other people using it, if this is your intention. 
Examples of open source license are MIT, GPL, BSD, Zlib.
Code is automatically copyrighted (and thus, not reusable) unless an explicit license is added.

**Comment by egonelbre** [comment]
Ah, thanks for reminding, somehow I forgot it. Will do :)

**Comment by egonelbre** [comment]
Done https://github.com/adinfinit/texpack/blob/master/LICENSE

**Comment by silverweed** [comment]
Thank you very much :)
